enum TokenType {
  KEYWORD = 'KEYWORD',
  VARIABLE = 'VARIABLE',
  OPERATOR = 'OPERATOR',
  BRACKET = 'BRACKET',
  INTEGER = 'INTEGER',
  STRING = 'STRING',
  FLOAT = 'FLOAT',
  BOOLEAN = 'BOOLEAN',
}

export default TokenType
